---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-service-poetry
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-service-poetry-app
  template:
    metadata:
      labels:
        app: grpc-service-poetry-app
    spec:
      containers:
      - name: grpc-service-poetry
        image: ahmedaminesoltani/grpc-service-poetry:v1
        ports:
        - containerPort: 4040
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-service-poetry-lb
spec:
  type: LoadBalancer 
  ports:
  - name: http
    port: 80
    targetPort: 4040
  selector:
    app: grpc-service-poetry-app